mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            logic-delete-value: 1
            logic-not-delete-value: 0
server:
    port: 8001
spring:
    application:
        name: mxy_system
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: Aa123456.
        url: jdbc:mysql://110.42.135.120:3306/mxy_blog?serverTimezone=GMT%2B8&useSSL=false
        username: root
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    profiles:
        active: dev
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
# JWT配置
jwt:
    # 密匙KEY
    secret: MXYSecret
    # HeaderKEY
    tokenHeader: Authorization
    # Token前缀字符
    tokenPrefix: Mxy-
    # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
    expiration: 86400
    # 配置不需要认证的接口
    antMatchers: /index/**,/sysArticle/**,/mxy/**,/favicon.ico
