# 配置端口
server:
    port: 8002
spring:
    application:
        name: mxy_security
    # 配置数据源
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: Aa123456.
        url: jdbc:mysql://110.42.135.120:3306/mxy_blog?serverTimezone=GMT%2B8
        username: root
# JWT配置
jwt:
    # 密匙KEY
    secret: JWTSecret
    # HeaderKEY
    tokenHeader: Authorization
    # Token前缀字符
    tokenPrefix: Sans-
    # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
    expiration: 86400
    # 配置不需要认证的接口
    antMatchers: /index,/login/**,/favicon.ico
